config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :games, only: [:index, :show, :new]
  end
  resources :systems, only: [:index, :show]
  resources :games
  post '/add_systems' => 'systems#add_systems'
  post '/games/:id/last_played' => 'games#last_played'
  post '/games/:id/add_game' => 'games#add_game'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#fb_login'
  root 'users#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :system
    has_many :user_games
    has_many :users, through: :user_games
    validates :name, presence: true
    validates :rating, presence: true
    scope :search, ->(s) {where("name LIKE ?", "%#{s}%")}
    
end

app/models/system.rb
class System < ApplicationRecord
    has_many :games
    has_many :user_systems
    has_many :users, through: :user_systems
    # validates :name, presence: true
    # validates :name, uniqueness: true
    # validates :company, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_systems
    has_many :user_games
    has_many :systems, through: :user_systems
    has_many :games, through: :user_games
    has_secure_password
    validates :username, presence: true
    validates :username, uniqueness: true
end

app/models/user_game.rb
class UserGame < ApplicationRecord
    belongs_to :user 
    belongs_to :game 
    # when user last played the game?
end

app/models/user_system.rb
class UserSystem < ApplicationRecord
    belongs_to :user 
    belongs_to :system 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper 
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    include GamesHelper
    before_action :logged_in
    before_action :set_game, only: [:edit, :update, :destroy, :add_game]

    def index
        if params[:user_id]
            @user = User.find_by(id: params[:user_id])
            if @user.nil?
              redirect_to users_path, alert: "User not found"
            else
              @games = @user.games
            end
        elsif params[:query]
            @games = Game.search(params[:query])
        else
            @games = Game.all
        end
    end

    def new 
        @game = Game.new
    end

    def create
        # refactor for build or create/find?
        @game = Game.new(game_params)
        if @game.valid?
            @game.creator = session[:user_id]
            @game.save
            users_game
            redirect_to game_path(@game)
        else
            render :new
        end
    end

    def show
        if params[:user_id]
            @user = User.find_by(id: params[:user_id])
            @game = @user.games.find_by(id: params[:id])
            if @game.nil?
              redirect_to user_games_path(@user), alert: "Game not found"
            end
        else
            set_game
        end
    end

    def edit
        redirect_to game_path(@game) unless @game.creator == session[:user_id]
    end

    def update
        redirect_to game_path(@game) unless @game.creator == session[:user_id]
        if @game.update(game_params)
            redirect_to game_path(@game)
        else
            render :edit
        end
    end

    def destroy
        set_users_game(@game).destroy
        redirect_to user_games_path(current_user.id)
    end

    def last_played
        @usersgame = UserGame.find_by(user_id: session[:user_id], game_id: params[:id])
        if @usersgame
            @usersgame.last_played = params[:input][:last_played]
            @usersgame.save
            redirect_to user_games_path(current_user.id)
        else
            redirect_to game_path(params[:id]), alert: "Have you played this game?"
        end
    end

    def add_game
        users_game
        redirect_to user_games_path(@user)
    end

    private

    def game_params
        params.require(:game).permit(:name, :rating, :description, :system_id)
    end

    def set_game
        @game = Game.find(params[:id])
    end

    def users_game
        @user = current_user
        @user.games << @game
        @user.save
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new 
    end

    def create
        user = User.find_by(username: params[:user][:username])
        if user && user.authenticate(params[:user][:password])
          session[:user_id] = user.id
          redirect_to user_path(user)
        else
            redirect_to "/login"
        end
    end

    def fb_login
        @user = User.find_or_create_by(uid: auth['uid']) do |u|
            u.username = auth['info']['name']
            u.password = auth['info']['email']
        end
        session[:user_id] = @user.id
        redirect_to "/"
    end

    def destroy
        session.delete :user_id
        redirect_to "/"
    end

    private

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
    before_action :logged_in

    def index
    end

    def show
        @system = System.find(params[:id])
    end

    def add_systems
        @user = User.find(session[:user_id])
        @user.update(system_params)
        redirect_to user_path(@user)
    end

    private

    def system_params
        params.require(:system).permit(system_ids:[])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in, only: [:index, :show, :edit, :update, :destroy]
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
        @users = User.all
    end

    def new 
        @user = User.new
    end

    def create
        if params[:user][:password] == params[:user][:password_confirmation] && params[:user][:password].strip != ""
            @user = User.new(user_params)
            if @user.save
                session[:user_id] = @user.id
                redirect_to user_path(@user)
            else
                render :new
            end
        else
            redirect_to new_user_path, alert: "passwords don't match"
        end
    end

    def show
    end

    def edit
       user_match
    end

    def update
        user_match
        if params[:user][:password] == params[:user][:password_confirmation] && params[:user][:password].strip != ""
            @user.update(user_params)
            if @user.save
                redirect_to user_path(@user)
            else
                render :edit
            end
        else
            redirect_to edit_user_path(@user), alert: "passwords don't match"
        end
    end

    def destroy
        user_match
        User.find(@user.id).destroy
        session.delete :user_id
        redirect_to new_user_path
    end

    def home
    end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :password)
    end

    def user_match
        redirect_to "/" unless @user.id == session[:user_id]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        User.find(session[:user_id])
    end

    def logged_in
        if !session.include? :user_id
            redirect_to new_user_path
        end
    end
end

app/helpers/games_helper.rb
module GamesHelper

    def time_played(game)
        user = User.find(session[:user_id])
        usergame = UserGame.find_by(user_id: user.id, game_id: game.id)
        if usergame
            usergame.last_played
        end
    end

    def set_users_game(game)
        user = User.find(session[:user_id])
        usergame = UserGame.find_by(user_id: user.id, game_id: game.id)
        usergame
    end
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %>
    <%= f.error_messages %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.error_message_on(:name) %><br>
    <%= f.label :rating %>
    <%= f.text_field :rating %>
    <%= f.error_message_on(:rating) %><br>
    <%= f.label :system %>
    <%= f.collection_select :system_id, System.all, :id, :name %><br>
    <%= f.label :description %>
    <%= f.text_area :description %><br>
    <%= f.submit %>
<% end %>

app/views/games/edit.html.erb
<h1>Edit Game</h1>

<%= render 'form' %>

app/views/games/index.html.erb
<% if @user %>
    <h1><%= @user.username %> Games</h1>
    <% @games.each do |x| %>
        <p><%= link_to x.name, game_path(x) %> Rating: <%= x.rating %> Last Played: <%= time_played(x) %></p><br>
    <% end %>
<% else %>
    <h1>Games</h1>
    <% @games.each do |x| %>
        <%= link_to x.name, game_path(x) %> Rating: <%= x.rating %><br>
    <% end %>
<% end %>


app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

app/views/games/show.html.erb
<h1><%= @game.name %></h1>

<p>Rated: <%= @game.rating %></p>
<p>System: <%= @game.system.name %></p>
<p>Info: <%= @game.description %></p> 

<% if set_users_game @game %>
    <%= form_for :input, url: "/games/#{@game.id}/last_played", method: "post" do |f| %>
        <%= f.label "Last Played:" %> 
        <%= time_played(@game) %>
        <%= f.text_field :last_played %>
        <%= f.submit "Update" %>
    <% end %>
    <br>
    <%= form_tag("/games/#{@game.id}", method: :delete) do %>
        <%= button_tag "Remove from library" %>
    <% end %>
<% else %>
    <%= form_tag("/games/#{@game.id}/add_game") do %>
        <%= button_tag "Add to library" %>
    <% end %>
<% end %>
<% if @game.creator == current_user.id %>
    <%= form_tag("/games/#{@game.id}/edit", method: :get) do %>
        <%= button_tag "Edit" %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GamersLibrary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <link rel="stylesheet" href="/stylesheets/main.css" />
  <header>
    <% if session[:user_id] %>
      <%= form_tag games_path, :method => "get" do %>
        <%= label_tag(:query, "Search Games") %>
        <%= text_field_tag :query, params[:query] %>
        <%= submit_tag("Search", :name => nil)%>
      <% end %>
      <%= form_tag("/logout", method: "post") do %>
        <%= button_tag "Log Out" %>
      <% end %>
      <%= link_to "Home", "/" %>
    <% else %>
        <h1>Welcome to Gamers Library!</h1>
    <% end %>
    <% if flash[:alert] %>
      <%= flash[:alert] %>
    <% end %>
  </header>
  <body>
    <%= yield %>
  </body>
</html>

app/views/systems/index.html.erb
<h1><%= current_user.username %> Systems</h1>
<br>
<%= form_for :system, url: "/add_systems", method: "post" do |f| %>
    <p><%= f.collection_check_boxes :system_ids, System.all, :id, :name, {:checked => current_user.systems.map(&:id)} %></p>
    <%= f.submit "Save Systems" %>
<% end %>

app/views/systems/show.html.erb
<h1><%= @system.name %></h1>
<h2>Company: <%= @system.company %></h2>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <%= f.error_messages %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.error_message_on(:username) %><br>
    <%= f.label :password %>
    <%= f.text_field :password %><br>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %><br>
    <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1> Edit User </h1>

<%= render 'form' %>

app/views/users/home.html.erb
<% if session[:user_id] %>
    <h2>Search for games in the search bar or check some links below</h2>
    <h2><%= link_to "All Games", games_path %></h2>
    <h2><%= link_to "Systems", systems_path %></h2>
    <h2><%= link_to "Profile", user_path(session[:user_id]) %></h2>
    <h3><%= link_to "All Users", users_path %></h3>
<% else %>
    <h1><%= link_to "Sign Up", new_user_path %></h1>
    or
    <h1><%= link_to "Login", "/login" %></h1>
<% end %>

app/views/users/index.html.erb
<h1>User Index</h1>
<br>
<% @users.each do |x| %>
    <h3><%= link_to x.username, user_path(x) %></h3>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<br>
<h1>Systems</h1>
<% @user.systems.each do |x| %>
    <p><%= x.name %> Company: <%= x.company %></p>
<% end %>
<% if @user.id == session[:user_id] %>
    <%= link_to "Edit Systems", systems_path %><br>
    <%= link_to "Add Games", "/games/new" %>
<% end %>

<br>
<h2><%= link_to "Game Library", user_games_path(@user) %></h2>
<br>
<% if @user.id == session[:user_id] %>
    <footer><%= link_to "Delete Account", "/users/#{session[:user_id]}", method: :delete %></footer>
<% end %>